### ISSUE TITLE
Support tree viewers for XML and JSON

### ISSUE THREAD

**Issue by mfulton26** [janodvarko/harviewer#62]
Pretty printed/formatted XML and JSON tree viewers with expandable/collapsible nodes, etc.

**Comment by gitgrimbo** [comment]
Hi, the following branch, http://gitgrimbo.github.io/harviewer/issue-62/, should have JSON and XML tree views.  There is syntax highlighting as well, but no pretty print.

Can you check it out with the HARs you were using please and let me know if you find any problems?  Thanks.

**Comment by mfulton26** [comment]
Nice. Most of the HAR files I tried worked well. One that didn't I exported from viewing http://www.npr.org/rss/podcast.php?id=510299 in Google Chrome (Save as HAR with content). It simply didn't show the XML tab for it in the viewer.

I like the tree viewer though. I wonder if there might be a simple and good way to make it so that the user can quickly expand an entire subtree. XML and JSON often have the meat of the data a few layers deep and iterating through an array of such objects would be tedious with several click per element. If there were a separate button or something to expand/collapse an entire section of the tree that would be great.

**Comment by gitgrimbo** [comment]
Hi, thanks for testing.

Can you supply a HAR that includes that XML file, or give me a link to a website that I can grab a HAR from?

I can't tell what's happening without a HAR, but my guess would be that the MIME type of that particular resource isn't recognised by HAR VIewer as XML.

It could be that it's better to let the user 'force view as XML' or something, rather than use MIME type comparisons.

**Comment by mfulton26** [comment]
http://www.npr.org/rss/podcast.php?id=510299

Personally I like the auto-detect based off of the MIME type but both could be done as well. Try to auto-detect but then have a drop-down to force a different view. You could even then support multiple viewers for a single type (e.g. a "pretty XML" vs a "tree XML", same for JSON).

**Comment by mfulton26** [comment]
[www.npr.org.har.zip](https://github.com/janodvarko/harviewer/files/339732/www.npr.org.har.zip) attached.

**Comment by gitgrimbo** [comment]
Cheers.

As I suspected, the MIME type is recorded in your HAR as `application/rss+xml`, but that branch of HAR Viewer only checks for `text/xml` and `application/xml`.

I guess a reasonable update would be to include the MIME types from https://en.wikipedia.org/wiki/XML_and_MIME:

- `application/atom+xml`
- `application/xslt+xml`
- `application/mathml+xml`
- `application/rss+xml`
- `application/xhtml+xml` (treated in HAR Viewer as HTML rather than XML)
- `image/svg+xml` (could be viewed in an ImageTab as well as XmlTab I guess)

But I'm guessing there are other popular XML MIME types that are missing from that list?  A force-view-as-xml option could satisfy the rest I guess.

**Comment by mfulton26** [comment]
Would it be safe to match against a pattern? e.g. `^application\/(?:xml|.+\+xml)$`

**Comment by gitgrimbo** [comment]
Yeah maybe.  I'm not a MIME/media type expert so unfortunately will have to think about it!

Just looking to see if https://www.npmjs.com/package/media-typer would be useful here ... if it's not an obvious XML media type then check the `suffix` for `xml`.

**Comment by gitgrimbo** [comment]
Hi, I've updated the branch http://gitgrimbo.github.io/harviewer/issue-62/ to recognise the XML types referenced above.

I've also fixed XML detection for syntax highlighting (but beware that syntax highlighting the 494.7 KB of your sample XML can take a while, so be patient with the browser!).

Hopefully it's what you're after.  If it is, I'll look to add to master.

**Comment by mfulton26** [comment]
Looks great to me.
